### ISSUE TITLE
Scatterplots do not scale well for p maps

### ISSUE THREAD

**Issue by chrisfilo** [vsoch/pybraincompare#15]
http://neurovault.org/images/compare/9631/3391

![screen shot 2015-05-26 at 23 46 33](https://cloud.githubusercontent.com/assets/238759/7830364/7a7eecc4-0401-11e5-81b5-b1701b1d7433.png)

**Comment by vsoch** [comment]
Each of these maps has a very small range of values clustered around zero:

This is the image on the y axis:

      In [35]: np.min(image1_vector[-np.isnan(image1_vector)])
      Out[35]: 2.2672422822838948e-22

      In [36]: np.max(image1_vector[-np.isnan(image1_vector)])
      Out[36]: 0.12566179037094111

And the x axis:

      In [37]: np.max(image2_vector[-np.isnan(image2_vector)])
      Out[37]: 0.027948727831244465

      In [38]: np.min(image2_vector[-np.isnan(image2_vector)])
      Out[38]: 0.0

The issue was a few lines of code added to prevent the dots from overlapping the axis:

https://github.com/vsoch/pybraincompare/blob/master/pybraincompare/template/html/scatter_atlas.html#L123

Here are the images above with this buffer removed:

![plot](https://cloud.githubusercontent.com/assets/814322/7841203/d3fe1114-044f-11e5-8e83-56e3e091b095.png)

I will test this on my local neurovault first, and do a fix soon!
